In [2]:
import numpy as np

In [3]:
import keras

In [4]:
keras.__version__

'2.5.0'

In [5]:
from keras.models import Sequential

In [6]:
from keras.datasets import mnist
from keras.layers import Dense, Dropout, Activation, Flatten

In [7]:
from keras.utils import np_utils # let label transit to 0ne-hot-encoding

In [8]:
from matplotlib import pyplot as plt
import cv2

In [9]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()  # grouping the minst's data to train and test group

11501568/11490434 [==============================] - 716s 62us/step


In [10]:
print(X_test.shape)  #there are 10000 test images, and the image is in 28 x 28 format

(10000, 28, 28)


In [11]:
print(y_test.shape) # the corresponging number with respect to 10000 images is 10000 as predicted

(10000,)


In [12]:
model = Sequential() # create linear implementing model

In [13]:
model.add(Dense(units=256, input_dim=784, kernel_initializer='normal', activation='relu')) # add input layer and hidden layer

In [14]:
model.add(Dense(units=10, kernel_initializer='normal', activation='softmax')) # add output layer


In [15]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']) # Compilation: Choose loss function, optimization method and effectiveness measurement method

In [16]:
y_TrainOneHot = np_utils.to_categorical(y_train)

In [17]:
_TestOneHot = np_utils.to_categorical(y_test)

In [18]:
X_train_2D = X_train.reshape(60000, 28*28).astype('float32')
X_test_2D = X_test.reshape(10000, 28*28).astype('float32') # 2D-1D

In [19]:
print(X_train.shape) #there are 10000 test images, and the image is in 28 x 28 format

(60000, 28, 28)


In [20]:
print(y_train.shape)

(60000,)


In [21]:
print("X_test_2D: ",X_test_2D.shape)

X_test_2D:  (10000, 784)


In [22]:
print('X_train_2d',X_train_2D.shape)

X_train_2d (60000, 784)


In [23]:
x_Train_norm = X_train_2D/255
x_Test_norm = X_test_2D/255 # important process

In [27]:
x_Train_norm = X_train_2D/255
x_Test_norm = X_test_2D/255 # important process

In [31]:
y_TestOneHot = None # define the y_Test

In [35]:
print(predictions)

[3 3 3 3 3 3 3 3 3]


In [36]:
train_history = model.fit(x=x_Train_norm, y=y_TrainOneHot, validation_split=0.2, epochs=100, batch_size=800, verbose=2)


Epoch 1/100
60/60 - 12s - loss: 0.7877 - accuracy: 0.8073 - val_loss: 0.3260 - val_accuracy: 0.9112
Epoch 2/100
60/60 - 2s - loss: 0.2995 - accuracy: 0.9164 - val_loss: 0.2482 - val_accuracy: 0.9315
Epoch 3/100
60/60 - 2s - loss: 0.2357 - accuracy: 0.9340 - val_loss: 0.2089 - val_accuracy: 0.9422
Epoch 4/100
60/60 - 2s - loss: 0.1956 - accuracy: 0.9451 - val_loss: 0.1801 - val_accuracy: 0.9506
Epoch 5/100
60/60 - 2s - loss: 0.1659 - accuracy: 0.9532 - val_loss: 0.1600 - val_accuracy: 0.9565
Epoch 6/100
60/60 - 2s - loss: 0.1428 - accuracy: 0.9597 - val_loss: 0.1461 - val_accuracy: 0.9591
Epoch 7/100
60/60 - 2s - loss: 0.1259 - accuracy: 0.9646 - val_loss: 0.1342 - val_accuracy: 0.9625
Epoch 8/100
60/60 - 2s - loss: 0.1101 - accuracy: 0.9700 - val_loss: 0.1232 - val_accuracy: 0.9646
Epoch 9/100
60/60 - 2s - loss: 0.0977 - accuracy: 0.9731 - val_loss: 0.1182 - val_accuracy: 0.9665
Epoch 10/100
60/60 - 2s - loss: 0.0875 - accuracy: 0.9766 - val_loss: 0.1103 - val_accuracy: 0.9678
Epoch 11

Epoch 83/100
60/60 - 2s - loss: 6.3762e-04 - accuracy: 1.0000 - val_loss: 0.0999 - val_accuracy: 0.9791
Epoch 84/100
60/60 - 2s - loss: 6.1175e-04 - accuracy: 1.0000 - val_loss: 0.0993 - val_accuracy: 0.9791
Epoch 85/100
60/60 - 2s - loss: 5.7846e-04 - accuracy: 1.0000 - val_loss: 0.0998 - val_accuracy: 0.9787
Epoch 86/100
60/60 - 2s - loss: 5.5722e-04 - accuracy: 1.0000 - val_loss: 0.1008 - val_accuracy: 0.9785
Epoch 87/100
60/60 - 2s - loss: 5.4083e-04 - accuracy: 1.0000 - val_loss: 0.1009 - val_accuracy: 0.9793
Epoch 88/100
60/60 - 2s - loss: 5.1641e-04 - accuracy: 1.0000 - val_loss: 0.1013 - val_accuracy: 0.9787
Epoch 89/100
60/60 - 1s - loss: 5.0192e-04 - accuracy: 1.0000 - val_loss: 0.1030 - val_accuracy: 0.9781
Epoch 90/100
60/60 - 2s - loss: 4.7671e-04 - accuracy: 1.0000 - val_loss: 0.1025 - val_accuracy: 0.9786
Epoch 91/100
60/60 - 1s - loss: 4.5855e-04 - accuracy: 1.0000 - val_loss: 0.1029 - val_accuracy: 0.9789
Epoch 92/100
60/60 - 2s - loss: 4.3627e-04 - accuracy: 1.0000 - 

In [37]:
scores = model.evaluate(x_Test_norm, y_TestOneHot)

313/313 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.0000e+00


In [38]:
print("\t[Info] Accuracy of testing data = {:2.1f}%".format(scores[1]*100.0))


	[Info] Accuracy of testing data = 0.0%


In [54]:
img=cv2.imread('/Users/apple/Downloads/Numbers.jpeg', cv2.IMREAD_GRAYSCALE) 

In [55]:
crop_size = (28, 28)
img = cv2.resize(img, crop_size, interpolation = cv2.INTER_CUBIC)

In [56]:
img_2D = img.reshape(1,28*28).astype('float32')
img_norm=img_2D/255
img = img_norm
predictions = model.predict_classes(img)

In [57]:
print(predictions)

[2]


In [58]:
train_history = model.fit(x=x_Train_norm, y=y_TrainOneHot, validation_split=0.2, epochs=20, batch_size=800, verbose=2)

Epoch 1/20
60/60 - 1s - loss: 1.4333e-04 - accuracy: 1.0000 - val_loss: 0.1129 - val_accuracy: 0.9786
Epoch 2/20
60/60 - 1s - loss: 1.3748e-04 - accuracy: 1.0000 - val_loss: 0.1138 - val_accuracy: 0.9784
Epoch 3/20
60/60 - 1s - loss: 1.3347e-04 - accuracy: 1.0000 - val_loss: 0.1136 - val_accuracy: 0.9787
Epoch 4/20
60/60 - 1s - loss: 1.2782e-04 - accuracy: 1.0000 - val_loss: 0.1142 - val_accuracy: 0.9789
Epoch 5/20
60/60 - 1s - loss: 1.2460e-04 - accuracy: 1.0000 - val_loss: 0.1149 - val_accuracy: 0.9785
Epoch 6/20
60/60 - 1s - loss: 1.2069e-04 - accuracy: 1.0000 - val_loss: 0.1150 - val_accuracy: 0.9788
Epoch 7/20
60/60 - 1s - loss: 1.1529e-04 - accuracy: 1.0000 - val_loss: 0.1154 - val_accuracy: 0.9783
Epoch 8/20
60/60 - 1s - loss: 1.1188e-04 - accuracy: 1.0000 - val_loss: 0.1155 - val_accuracy: 0.9788
Epoch 9/20
60/60 - 1s - loss: 1.0932e-04 - accuracy: 1.0000 - val_loss: 0.1160 - val_accuracy: 0.9787
Epoch 10/20
60/60 - 2s - loss: 1.0404e-04 - accuracy: 1.0000 - val_loss: 0.1170 - 

In [59]:
X = x_Test_norm[0:10,:]

In [60]:
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [61]:
predictions = model.predict_classes(X)

In [62]:
print(predictions)

[7 2 1 0 4 1 4 9 5 9]


In [63]:
cv2.imshow("image", img)

In [ ]:
cv2.waitKey(0)